---------------- MODULE FdLeaseImplementationTopology ----------------
EXTENDS FiniteSets

\* Generated by pal.foundation.fd_lease_formal; do not edit by hand.
TransitionTopologyDigest == "5edbc5a0b96ad3dab5cd7b810d19cf7e425eda1df2a067df75b045a00ca05069"

ControlStates == {"OPEN", "RETIRING", "CLOSING", "REVOKING", "CLOSED", "QUARANTINED"}
ControlTransitions == {
    <<"CLOSED", "PUBLISH", "OPEN">>,
    <<"CLOSING", "CLOSE_DETACHED", "CLOSED">>,
    <<"CLOSING", "CLOSE_UNCERTAIN", "QUARANTINED">>,
    <<"OPEN", "REQUEST_RETIRE", "RETIRING">>,
    <<"RETIRING", "CLAIM_GRACEFUL_CLOSE", "CLOSING">>,
    <<"RETIRING", "FORCE_REVOKE", "REVOKING">>,
    <<"REVOKING", "CLOSE_DETACHED", "CLOSED">>,
    <<"REVOKING", "CLOSE_UNCERTAIN", "QUARANTINED">>
}
CapabilityStates == {"LIVE", "CANCELLED", "TOMBSTONE", "RELEASED"}
CapabilityTransitions == {
    <<"CANCELLED", "FORCE_REVOKE", "TOMBSTONE">>,
    <<"CANCELLED", "RELEASE", "RELEASED">>,
    <<"LIVE", "FORCE_REVOKE", "TOMBSTONE">>,
    <<"LIVE", "RELEASE", "RELEASED">>,
    <<"LIVE", "REQUEST_CANCEL", "CANCELLED">>,
    <<"LIVE", "RETIRE_CANCEL", "CANCELLED">>,
    <<"TOMBSTONE", "RELEASE", "RELEASED">>
}
ControlEdge(source, action, target) ==
    <<source, action, target>> \in ControlTransitions
CapabilityEdge(source, action, target) ==
    <<source, action, target>> \in CapabilityTransitions

TransitionsWellFormed ==
    /\ \A edge \in ControlTransitions :
           /\ edge[1] \in ControlStates /\ edge[3] \in ControlStates
    /\ \A edge \in CapabilityTransitions :
           /\ edge[1] \in CapabilityStates /\ edge[3] \in CapabilityStates
ClosedOnlyPublishes ==
    \A edge \in ControlTransitions :
        edge[1] = "CLOSED" => edge = <<"CLOSED", "PUBLISH", "OPEN">>
QuarantineIsTerminal ==
    ~\E edge \in ControlTransitions : edge[1] = "QUARANTINED"
CloseClaimPathsAreExplicit ==
    /\ <<"RETIRING", "CLAIM_GRACEFUL_CLOSE", "CLOSING">> \in ControlTransitions
    /\ <<"RETIRING", "FORCE_REVOKE", "REVOKING">> \in ControlTransitions
PublicationPathIsExplicit ==
    <<"CLOSED", "PUBLISH", "OPEN">> \in ControlTransitions

=============================================================================
