------------- MODULE EndpointHubImplementationReducer -------------
EXTENDS FiniteSets

\* Generated from pal.channel.lifecycle.reduce_endpoint_hub; do not edit.
ReducerDigest == "1642b386906602ba69d8dc405f0d269853398fc0f970847793f3c92bd86266f1"

HubStates == {"absent", "discovered", "transitioning", "draining", "attached", "detached", "degraded", "removing"}
HubActions == {"DISCOVER", "REQUEST_PUBLISH", "WITHDRAW", "BEGIN_TRANSITION", "REGISTER_TRANSPORT", "BEGIN_DRAIN", "DRAIN_COMPLETE", "TRANSITION_FAILED", "DETACH_COMPLETE", "ROLLBACK_TRANSPORT", "TRANSPORT_REMOVED", "BEGIN_REMOVE", "REMOVE_COMPLETE"}
HubReducerEdges == {
    <<"absent", FALSE, FALSE, FALSE, FALSE, TRUE, "DISCOVER", "discovered", TRUE, FALSE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, FALSE, FALSE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, FALSE, FALSE, FALSE, "REQUEST_PUBLISH", "attached", TRUE, TRUE, FALSE, TRUE>>,
    <<"attached", TRUE, TRUE, FALSE, FALSE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, FALSE, FALSE, FALSE, "WITHDRAW", "attached", TRUE, TRUE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, FALSE, FALSE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, FALSE, FALSE, TRUE, "REQUEST_PUBLISH", "attached", TRUE, TRUE, TRUE, TRUE>>,
    <<"attached", TRUE, TRUE, FALSE, FALSE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, FALSE, FALSE, TRUE, "WITHDRAW", "attached", TRUE, TRUE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, FALSE, TRUE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"attached", TRUE, TRUE, FALSE, TRUE, FALSE, "REQUEST_PUBLISH", "attached", TRUE, TRUE, FALSE, TRUE>>,
    <<"attached", TRUE, TRUE, FALSE, TRUE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, FALSE, TRUE, FALSE, "WITHDRAW", "attached", TRUE, TRUE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, TRUE, TRUE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"attached", TRUE, TRUE, TRUE, TRUE, FALSE, "REQUEST_PUBLISH", "attached", TRUE, TRUE, FALSE, TRUE>>,
    <<"attached", TRUE, TRUE, TRUE, TRUE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, TRUE, TRUE, FALSE, "WITHDRAW", "attached", TRUE, TRUE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, TRUE, TRUE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"attached", TRUE, TRUE, TRUE, TRUE, TRUE, "REQUEST_PUBLISH", "attached", TRUE, TRUE, TRUE, TRUE>>,
    <<"attached", TRUE, TRUE, TRUE, TRUE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"attached", TRUE, TRUE, TRUE, TRUE, TRUE, "WITHDRAW", "attached", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, FALSE, "BEGIN_REMOVE", "removing", FALSE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, FALSE, "REQUEST_PUBLISH", "degraded", TRUE, FALSE, FALSE, TRUE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, FALSE, "WITHDRAW", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, TRUE, "BEGIN_REMOVE", "removing", FALSE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, TRUE, "REQUEST_PUBLISH", "degraded", TRUE, FALSE, FALSE, TRUE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, FALSE, TRUE, "WITHDRAW", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, FALSE, "REQUEST_PUBLISH", "degraded", TRUE, FALSE, FALSE, TRUE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, FALSE, "WITHDRAW", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, TRUE, "REQUEST_PUBLISH", "degraded", TRUE, FALSE, FALSE, TRUE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, FALSE, FALSE, TRUE, TRUE, "WITHDRAW", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, FALSE, "REQUEST_PUBLISH", "degraded", TRUE, TRUE, FALSE, TRUE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, FALSE, "WITHDRAW", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, TRUE, "REQUEST_PUBLISH", "degraded", TRUE, TRUE, FALSE, TRUE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, FALSE, TRUE, "WITHDRAW", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, FALSE, "REQUEST_PUBLISH", "degraded", TRUE, TRUE, FALSE, TRUE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, FALSE, "WITHDRAW", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, TRUE, "REQUEST_PUBLISH", "degraded", TRUE, TRUE, FALSE, TRUE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"degraded", TRUE, TRUE, FALSE, TRUE, TRUE, "WITHDRAW", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, FALSE, "BEGIN_REMOVE", "removing", FALSE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, FALSE, "REQUEST_PUBLISH", "detached", TRUE, FALSE, FALSE, TRUE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, FALSE, "WITHDRAW", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, TRUE, "BEGIN_REMOVE", "removing", FALSE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, TRUE, "REQUEST_PUBLISH", "detached", TRUE, FALSE, FALSE, TRUE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, FALSE, TRUE, "WITHDRAW", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, FALSE, "REQUEST_PUBLISH", "detached", TRUE, FALSE, FALSE, TRUE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, FALSE, "WITHDRAW", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, TRUE, "REQUEST_PUBLISH", "detached", TRUE, FALSE, FALSE, TRUE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"detached", TRUE, FALSE, FALSE, TRUE, TRUE, "WITHDRAW", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, FALSE, "BEGIN_REMOVE", "removing", FALSE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, FALSE, "REQUEST_PUBLISH", "discovered", TRUE, FALSE, FALSE, TRUE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, FALSE, "WITHDRAW", "discovered", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, TRUE, "BEGIN_REMOVE", "removing", FALSE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, TRUE, "REQUEST_PUBLISH", "discovered", TRUE, FALSE, FALSE, TRUE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, FALSE, TRUE, "WITHDRAW", "discovered", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, FALSE, "REQUEST_PUBLISH", "discovered", TRUE, FALSE, FALSE, TRUE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, FALSE, "WITHDRAW", "discovered", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, TRUE, "REQUEST_PUBLISH", "discovered", TRUE, FALSE, FALSE, TRUE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"discovered", TRUE, FALSE, FALSE, TRUE, TRUE, "WITHDRAW", "discovered", TRUE, FALSE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, FALSE, "REQUEST_PUBLISH", "draining", TRUE, TRUE, FALSE, TRUE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, FALSE, "WITHDRAW", "draining", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, TRUE, "DRAIN_COMPLETE", "attached", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, TRUE, "REQUEST_PUBLISH", "draining", TRUE, TRUE, FALSE, TRUE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, FALSE, TRUE, "WITHDRAW", "draining", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, FALSE, "REQUEST_PUBLISH", "draining", TRUE, TRUE, FALSE, TRUE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, FALSE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, FALSE, "WITHDRAW", "draining", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, TRUE, "DRAIN_COMPLETE", "attached", TRUE, TRUE, TRUE, TRUE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, TRUE, "REQUEST_PUBLISH", "draining", TRUE, TRUE, FALSE, TRUE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, TRUE, "TRANSPORT_REMOVED", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"draining", TRUE, TRUE, FALSE, TRUE, TRUE, "WITHDRAW", "draining", TRUE, TRUE, FALSE, FALSE>>,
    <<"removing", FALSE, FALSE, FALSE, FALSE, TRUE, "REMOVE_COMPLETE", "absent", FALSE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, FALSE, "BEGIN_REMOVE", "removing", FALSE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, FALSE, "DETACH_COMPLETE", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, FALSE, "REGISTER_TRANSPORT", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, FALSE, "REQUEST_PUBLISH", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, FALSE, "TRANSPORT_REMOVED", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, FALSE, "WITHDRAW", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, TRUE, "BEGIN_REMOVE", "removing", FALSE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, TRUE, "DETACH_COMPLETE", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, TRUE, "REGISTER_TRANSPORT", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, TRUE, "REQUEST_PUBLISH", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, TRUE, "TRANSPORT_REMOVED", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, FALSE, TRUE, "WITHDRAW", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, FALSE, "DETACH_COMPLETE", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, FALSE, "REGISTER_TRANSPORT", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, FALSE, "REQUEST_PUBLISH", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, FALSE, "TRANSPORT_REMOVED", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, FALSE, "WITHDRAW", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, TRUE, "DETACH_COMPLETE", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, TRUE, "REGISTER_TRANSPORT", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, TRUE, "REQUEST_PUBLISH", "transitioning", TRUE, FALSE, FALSE, TRUE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, TRUE, "TRANSPORT_REMOVED", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, FALSE, FALSE, TRUE, TRUE, "WITHDRAW", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, FALSE, "BEGIN_DRAIN", "draining", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, FALSE, "DETACH_COMPLETE", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, FALSE, "REGISTER_TRANSPORT", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, FALSE, "REQUEST_PUBLISH", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, FALSE, "ROLLBACK_TRANSPORT", "draining", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, FALSE, "TRANSPORT_REMOVED", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, FALSE, "WITHDRAW", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, TRUE, "BEGIN_DRAIN", "draining", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, TRUE, "DETACH_COMPLETE", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, TRUE, "REGISTER_TRANSPORT", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, TRUE, "REQUEST_PUBLISH", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, TRUE, "ROLLBACK_TRANSPORT", "draining", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, TRUE, "TRANSPORT_REMOVED", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, FALSE, TRUE, "WITHDRAW", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, FALSE, "BEGIN_DRAIN", "draining", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, FALSE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, FALSE, "DETACH_COMPLETE", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, FALSE, "REGISTER_TRANSPORT", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, FALSE, "REQUEST_PUBLISH", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, FALSE, "ROLLBACK_TRANSPORT", "draining", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, FALSE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, FALSE, "TRANSPORT_REMOVED", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, FALSE, "WITHDRAW", "transitioning", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, TRUE, "BEGIN_DRAIN", "draining", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, TRUE, "BEGIN_TRANSITION", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, TRUE, "DETACH_COMPLETE", "detached", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, TRUE, "REGISTER_TRANSPORT", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, TRUE, "REQUEST_PUBLISH", "transitioning", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, TRUE, "ROLLBACK_TRANSPORT", "draining", TRUE, TRUE, FALSE, TRUE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, TRUE, "TRANSITION_FAILED", "degraded", TRUE, TRUE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, TRUE, "TRANSPORT_REMOVED", "transitioning", TRUE, FALSE, FALSE, FALSE>>,
    <<"transitioning", TRUE, TRUE, FALSE, TRUE, TRUE, "WITHDRAW", "transitioning", TRUE, TRUE, FALSE, FALSE>>
}
HubStep(sourceState, sourcePhysical, sourceTransport, sourcePublished,
        sourceIntent, bufferEmpty, action, targetState, targetPhysical,
        targetTransport, targetPublished, targetIntent) ==
    <<sourceState, sourcePhysical, sourceTransport, sourcePublished,
      sourceIntent, bufferEmpty, action, targetState, targetPhysical,
      targetTransport, targetPublished, targetIntent>> \in HubReducerEdges

ReducerWellFormed ==
    \A edge \in HubReducerEdges :
        /\ edge[1] \in HubStates
        /\ edge[2] \in BOOLEAN
        /\ edge[3] \in BOOLEAN
        /\ edge[4] \in BOOLEAN
        /\ edge[5] \in BOOLEAN
        /\ edge[6] \in BOOLEAN
        /\ edge[7] \in HubActions
        /\ edge[8] \in HubStates
        /\ edge[9] \in BOOLEAN
        /\ edge[10] \in BOOLEAN
        /\ edge[11] \in BOOLEAN
        /\ edge[12] \in BOOLEAN
ReducerNeverPublishesBeforeReady ==
    \A edge \in HubReducerEdges :
        edge[11] =>
            /\ edge[8] = "attached"
            /\ edge[9]
            /\ edge[10]
            /\ edge[6]
ReducerRemovalOwnsNothing ==
    \A edge \in HubReducerEdges :
        edge[8] \in {"absent", "removing"} =>
            /\ ~edge[9]
            /\ ~edge[10]
            /\ ~edge[11]
            /\ ~edge[12]

=============================================================================
