"""LSP session operations and diagnostics consumed by the manager."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class LspConnectorPort(Protocol):
    @property
    def workspace_root(self) -> Path: ...

    @property
    def extra_args(self) -> tuple[str, ...]: ...

    @property
    def healthy(self) -> bool: ...

    @property
    def server_info(self) -> dict[str, Any]: ...

    async def initialize(self) -> None: ...

    async def close(self) -> None: ...

    def stderr_tail_text(self) -> str: ...

    async def request(self, method: str, params: dict[str, Any]) -> dict[str, Any]: ...

    async def ensure_document_open(self, file_path: Path, *, language_id: str) -> dict[str, Any]: ...

    async def diagnostics(self, file_path: Path, *, language_id: str) -> dict[str, Any]: ...
