from __future__ import annotations

import hashlib
import json

from pal.foundation.fd_lease import (
    FD_CAPABILITY_TRANSITIONS,
    FD_CONTROL_TRANSITIONS,
    FdCapabilityState,
    FdControlState,
)


def _topology_digest() -> str:
    payload = {
        "capability": sorted(
            (source.value, action, target.value)
            for source, action, target in FD_CAPABILITY_TRANSITIONS
        ),
        "control": sorted(
            (source.value, action, target.value)
            for source, action, target in FD_CONTROL_TRANSITIONS
        ),
    }
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("ascii")
    ).hexdigest()


def _tla_set(rows: list[tuple[str, str, str]]) -> str:
    lines = ["{"]
    for index, row in enumerate(rows):
        suffix = "," if index + 1 < len(rows) else ""
        lines.append("    <<" + ", ".join(json.dumps(item) for item in row) + ">>" + suffix)
    lines.append("}")
    return "\n".join(lines)


def render_fd_lease_implementation_topology() -> str:
    control_states = "{" + ", ".join(json.dumps(item.value) for item in FdControlState) + "}"
    control_edges = _tla_set(
        sorted(
            (source.value, action, target.value)
            for source, action, target in FD_CONTROL_TRANSITIONS
        )
    )
    capability_states = (
        "{" + ", ".join(json.dumps(item.value) for item in FdCapabilityState) + "}"
    )
    capability_edges = _tla_set(
        sorted(
            (source.value, action, target.value)
            for source, action, target in FD_CAPABILITY_TRANSITIONS
        )
    )
    return "\n".join(
        (
            "---------------- MODULE FdLeaseImplementationTopology ----------------",
            "EXTENDS FiniteSets",
            "",
            "\\* Generated by pal.foundation.fd_lease_formal; do not edit by hand.",
            f"TransitionTopologyDigest == {json.dumps(_topology_digest())}",
            "",
            f"ControlStates == {control_states}",
            f"ControlTransitions == {control_edges}",
            f"CapabilityStates == {capability_states}",
            f"CapabilityTransitions == {capability_edges}",
            "ControlEdge(source, action, target) ==",
            "    <<source, action, target>> \\in ControlTransitions",
            "CapabilityEdge(source, action, target) ==",
            "    <<source, action, target>> \\in CapabilityTransitions",
            "",
            "TransitionsWellFormed ==",
            "    /\\ \\A edge \\in ControlTransitions :",
            "           /\\ edge[1] \\in ControlStates /\\ edge[3] \\in ControlStates",
            "    /\\ \\A edge \\in CapabilityTransitions :",
            "           /\\ edge[1] \\in CapabilityStates /\\ edge[3] \\in CapabilityStates",
            "ClosedOnlyPublishes ==",
            "    \\A edge \\in ControlTransitions :",
            "        edge[1] = \"CLOSED\" => edge = <<\"CLOSED\", \"PUBLISH\", \"OPEN\">>",
            "QuarantineIsTerminal ==",
            "    ~\\E edge \\in ControlTransitions : edge[1] = \"QUARANTINED\"",
            "CloseClaimPathsAreExplicit ==",
            "    /\\ <<\"RETIRING\", \"CLAIM_GRACEFUL_CLOSE\", \"CLOSING\">> \\in ControlTransitions",
            "    /\\ <<\"RETIRING\", \"FORCE_REVOKE\", \"REVOKING\">> \\in ControlTransitions",
            "PublicationPathIsExplicit ==",
            "    <<\"CLOSED\", \"PUBLISH\", \"OPEN\">> \\in ControlTransitions",
            "",
            "=============================================================================",
            "",
        )
    )


__all__ = ["render_fd_lease_implementation_topology"]
