from __future__ import annotations

from pal.skill.contracts import SkillApplicabilitySTAR, SkillDescriptor


PAL_PLUGIN_DEVELOPMENT_SKILL_ID = "pal.plugin.development"
PAL_LLM_ADAPTER_ENDPOINT_DEVELOPMENT_SKILL_ID = "pal.llm.adapter_endpoint.development"
PAL_CHANNEL_PROVIDER_DEVELOPMENT_SKILL_ID = "pal.channel.provider.development"
PAL_LSP_TEMPLATE_DEVELOPMENT_SKILL_ID = "pal.lsp.template.development"


PAL_PLUGIN_DEVELOPMENT_MANUAL = """# Pal Plugin Development

Use this skill when Pal needs to create, review, repair, or explain a Pal plugin and cannot rely on direct source-code access.

## Goal

A Pal plugin is a sidecar extension that adds capabilities, prompt fragments, providers, event sources, event handlers, or control handlers without editing Pal core. Prefer a plugin when the requested feature is optional, detachable, hot-refreshable, or owned by a domain boundary outside core.

Do not make a plugin for behavior that belongs in the runtime bus itself, the shared message contracts, or the security/control plane. Core should stay a coordinator; plugins should own feature behavior.

## Community Plugin Layout

Put community plugins under the runtime root:

```text
<runtime_root>/plugins/community/<plugin_id>/
  plugin.toml
  runtime.py
  capabilities.py        # optional, but recommended for capability providers
  README.md              # optional human notes
```

Use a unique `plugin_id`. Avoid reusing first-party IDs.

Minimal `plugin.toml`:

```toml
plugin_id = "demo_tools"
entrypoint = "runtime"
version = "0.1.0"
enabled_by_default = true
```

Optional:

```toml
reload_modules = ["runtime", "capabilities"]
```

For community plugins, Pal clears modules loaded from the plugin directory during refresh. `reload_modules` is still useful when the plugin imports helper modules through stable names.

## Runtime Entrypoint

The entrypoint module must expose `build_plugin`. Pal calls it by name-aware dependency injection. Supported argument names include:

- `context`: a `PluginBuildContext` containing `runtime_root`, `services`, and `plugin_dir`.
- `runtime_root`: the Pal runtime root path.
- `plugin_dir`: this plugin directory.
- any service name present in the plugin host service map, such as `memory_service`.

Example `runtime.py`:

```python
from dataclasses import dataclass

from pal.core.module_registry import MODULE_TIER_DETACHABLE, ModuleHandle
from capabilities import DemoProvider


@dataclass
class DemoPluginBundle:
    plugin_id: str = "demo_tools"
    version: str = "0.1.0"

    def register_with_core(self, context):
        provider = DemoProvider()
        handle = ModuleHandle(
            module_id="demo_tools",
            tier=MODULE_TIER_DETACHABLE,
            detachable=True,
            introspection_provider=provider,
            supports_lifecycle_capabilities=True,
        )
        context.register_module(handle)
        return handle


def build_plugin(context=None, runtime_root=None, plugin_dir=None):
    return DemoPluginBundle()
```

## Capability Provider

Expose operations by combining `@capability_node` on the provider class and `@capability_action` on methods. Use `CapabilityCall` for operation calls and return `CapabilityResult` with non-empty `llm_text`.

Example `capabilities.py`:

```python
from dataclasses import dataclass

from pal.execution.contracts import CapabilityCall, CapabilityResult
from pal.shared import OPERATION_NAMESPACE, RuntimeStatus, capability_action, capability_node


@capability_node(
    namespace=OPERATION_NAMESPACE,
    scope="module",
    kind="module",
    source="plugin:demo_tools",
    target_kind="module",
)
@dataclass
class DemoProvider:
    module_id: str = "demo_tools"

    @capability_action(
        namespace=OPERATION_NAMESPACE,
        scope="module",
        family="demo",
        action_name="echo",
        description="Echo a short message.",
        args_schema={
            "type": "object",
            "properties": {"message": {"type": "string"}},
            "required": ["message"],
        },
    )
    def echo(self, call: CapabilityCall) -> CapabilityResult:
        message = str(call.args.get("message") or "")
        return CapabilityResult(
            status=RuntimeStatus.OK,
            text=message,
            structured={"message": message},
            llm_text=f"Echo: {message}",
        )
```

The canonical capability name is generated by the capability forest. Search for it with `op_tool_search` instead of guessing.

## Registering Other Surfaces

`ModuleHandle` is the plugin's contract with core:

- `introspection_provider`: capability provider.
- `prompt_fragment_providers`: prompt fragments owned by this module.
- `event_sources`: event sources owned by this module.
- `event_handlers`: event handlers keyed by event kind.
- `control_action_handlers`: deterministic control action handlers.
- `provider_refs`: named providers that execution runtime may route to.
- `ports`: internal service ports exposed as `<module_id>:<port_name>`.
- `cleanup_callbacks`: cleanup functions called on detach.

Keep each surface owned by the plugin's `module_id` so detach can withdraw the full subtree.

## Lifecycle and Hot Refresh

Attach, detach, and reattach must be clean:

1. Build a fresh bundle through `build_plugin`.
2. Return a `ModuleHandle` whose module ID is stable.
3. Let core/plugin host publish and withdraw capabilities; do not manually mutate the compiled index.
4. Put external resources in `cleanup_callbacks` or provider `detach` methods.
5. After code changes, use plugin detach/attach or core module reattach to load a fresh instance.

Useful operations:

- `op_plugin_mgmt_rescan`: discover plugin manifests.
- `op_plugin_mgmt_attach`: attach or refresh a plugin.
- `op_plugin_mgmt_detach`: detach a plugin.
- `op_plugin_mgmt_enable`: enable and attach a disabled plugin.
- `op_tool_search`: find capabilities after attach.
- `op_tool_call`: call a capability by discovered name.

## Safety and Product Rules

- Do not ask the user to do work Pal can do with existing capabilities.
- Do not bypass approval, access, identity, or constitutional boundaries.
- For high-risk actions, destructive filesystem changes, credentials, public network changes, or persistent system changes, route through the control/approval path.
- Keep large outputs in files or artifacts. Return short summaries and file paths.
- Prefer structured APIs over fragile string scraping.
- Keep plugin state in plugin-owned storage or the runtime root, not in Pal core globals.
- Use stable, minimal capability schemas. A small predictable tool beats a broad ambiguous one.
- Treat hardware, local devices, OS services, subprocesses, and network listeners as high-risk side effects. They must be behind explicit capability actions, admission checks, and approval policy when appropriate.
- `build_plugin` must not start unmanaged background work, touch hardware, mutate secrets, or perform irreversible I/O. It should construct providers and register lifecycle-owned resources only.
- Any sidecar, device handle, watcher, thread, task, or subprocess must be owned by the plugin lifecycle and stopped through `cleanup_callbacks` or provider detach. Detach must leave no live worker behind.
- Never leak credentials, raw device identifiers, tokens, private paths, or full hardware state into introspection. Expose minimal health/status fields and structured errors.

## Verification Checklist

Before calling the plugin done:

1. `op_plugin_mgmt_rescan` sees the manifest with no scan errors.
2. `op_plugin_mgmt_attach` returns ok and the plugin record is attached.
3. `op_tool_search` finds the new capability or prompt/source surface.
4. A representative capability call returns structured data and useful `llm_text`.
5. Detach removes the capability from discovery.
6. Attach again creates a fresh instance and restores the capability.
7. The plugin does not require the user to run commands manually unless approval or credentials are genuinely needed.
"""


PAL_LLM_ADAPTER_ENDPOINT_DEVELOPMENT_MANUAL = """# Pal LLM Adapter and Endpoint Development

Use this skill when Pal needs to add, review, repair, or explain an LLM provider adapter and its matching `llm_endpoints` row.

## Boundary

LLM provider adapters belong to the `llm` subsystem, not the plugin system. Do not create a Pal plugin for LLM transport behavior. Do not register adapters through `PluginHost`, `PluginBuildContext.services`, capability providers, prompt fragments, or global side effects outside `pal.llm`.

The production refresh/load step is user-controlled. You may prepare files, propose endpoint rows, and run isolated tests, but you must not execute `/refresh_llm_endpoints`, call `refresh_llm_endpoints`, set the active endpoint, or otherwise load the adapter into the running Pal runtime without explicit user direction. Final handoff must tell the user that refresh is required and list exactly what to refresh.

## Runtime Adapter Location

Put runtime-root adapter source under:

```text
<runtime_root>/llm/adapters/
```

Supported layouts:

```text
<runtime_root>/llm/adapters/my_provider.py
<runtime_root>/llm/adapters/my_provider/adapter.py
```

Each adapter module should define one or more `LLMProviderAdapter` subclasses. Explicit exports are allowed:

```python
ADAPTER = MyProviderAdapter
ADAPTERS = (MyProviderAdapter, OtherProviderAdapter)
```

## Adapter Contract

Keep adapter code small and deterministic. It should translate Pal's canonical request and endpoint metadata into LiteLLM kwargs, not perform network calls, mutate databases, read secrets, or import PalCore internals.

Minimal adapter:

```python
from pal.llm import CanonicalLLMRequest, LLMProviderAdapter, LiteLLMCompletionDraft


class MyProviderAdapter(LLMProviderAdapter):
    provider_names = frozenset({"my_provider"})
    adapter_names = frozenset({"my_provider"})
    litellm_provider = "openai"
    model_provider_aliases = frozenset({"openai"})

    def apply_request(self, request: CanonicalLLMRequest, draft: LiteLLMCompletionDraft) -> None:
        if request.metadata.get("think_level") == "off":
            draft.extra_body["thinking"] = {"type": "disabled"}
```

Use `provider_names` for endpoint `provider` matching. Use `adapter_names` when an endpoint sets `capabilities_blob.adapter` or `capabilities_blob.llm_adapter`. Use `litellm_provider` and `model_provider_aliases` to normalize `model_id` into the provider prefix LiteLLM expects.

## Endpoint Row

Create or update endpoint metadata only after checking the existing endpoint list. Required fields include:

- `endpoint_id`: stable unique ID, such as `my_provider_gpt_5`.
- `provider`: must match the adapter `provider_names` unless `capabilities_blob.adapter` selects the adapter.
- `model_id`: model name or LiteLLM-prefixed model, such as `my-model` or `openai/my-model`.
- `api_mode`: normally `openai_chat`; use `anthropic_messages` only for Anthropic-shaped endpoints.
- `base_url`: provider base URL, without credentials.
- `auth_kind`: `api_key_ref`, `oauth`, or `local_provider_auth`.
- `credential_ref`: secret reference such as `my_provider:api-key`; never store the key in the adapter.
- capability flags: `supports_tools`, `supports_streaming`, `supports_reasoning`, `supports_vision`, and optional `capabilities_blob`.

Prefer preparing a clear endpoint patch or SQL preview when no dedicated endpoint-management capability exists. Mutating the production database or secrets requires explicit user approval.

## Verification Workflow

Before asking the user to refresh:

1. Inspect the current `pal.llm.adapters.LLMProviderAdapter` contract and existing endpoint shape.
2. Write adapter source in the runtime-root adapter directory.
3. Compile the adapter file with `python -m py_compile <adapter_file>`.
4. Load it only in an isolated registry or subprocess, not the live Pal runtime.
5. Build a representative `LiteLLMEndpointInvoker(...)._build_completion_kwargs(...)` payload with a fake or test endpoint.
6. Assert model prefix, `api_base`, auth behavior, tools, `tool_choice`, `temperature`, max tokens, reasoning/thinking fields, and vendor-specific `extra_body`.
7. Confirm the adapter does not import plugin, channel, control, service, or PalCore internals.
8. If endpoint metadata changes are needed, verify them against a temporary database or produce an exact patch for user approval.
9. Do not switch the active endpoint during development.

## Handoff

When the adapter and endpoint are ready, report:

- adapter file path and endpoint ID
- tests or smoke checks run
- endpoint/database/secret changes made or still pending
- any load errors found in isolated checks
- a clear statement: "I did not refresh the running Pal runtime. Please run `/refresh_llm_endpoints` when you want to load this adapter."

If the user explicitly asks you to refresh, then use the normal LLM refresh path and report `provider_adapter_load_errors` if present.
"""


PAL_CHANNEL_PROVIDER_DEVELOPMENT_MANUAL = """# Pal Channel Provider Development

Use this skill when Pal needs to add, review, repair, or explain a channel integration, channel endpoint, or runtime-root channel provider.

## Boundary

Channel providers belong to the `channel` subsystem. They are not ordinary Pal plugins, even though built-in channels can be packaged by first-party plugins. The `ChannelEndpointProviderManager` is the single LLM/core-facing management entrypoint. A provider owns the concrete endpoint lifecycle and endpoint-specific introspection.

Keep these boundaries:

- `channel_kind` is a persisted endpoint type discriminator used by `channel_endpoints`; it should not become the LLM-facing abstraction.
- `ChannelEndpointProviderManager` maps endpoint type keys to providers and dispatches attach, detach, restart, inspect, auth, backlog, and health by endpoint id.
- The provider decides how attach/detach/restart/introspection work for its channel.
- Endpoint implementations normalize ingress, send replies, report auth/health/backlog, and render any channel-specific interactions.
- Do not put channel transport logic in `core`, `control`, `llm`, or `memory`.

## Runtime Provider Location

Runtime-root channel providers live under:

```text
<runtime_root>/channel/providers/<provider_id>/
  provider.toml
  runtime.py
  README.md        # optional
```

Do not create a second discovery layout unless the channel manager explicitly supports it.

Minimal `provider.toml`:

```toml
provider_id = "demo_chat"
entrypoint = "runtime.py"
version = "0.1.0"
enabled = true

reload_modules = ["runtime"]
```

`provider_id` must be stable and unique. `entrypoint` must point to a Python file inside the provider directory. `enabled = false` keeps the provider discoverable on disk but not loaded. `reload_modules` is advisory for endpoint restart and hot-refresh diagnostics.

## Provider Entrypoint

The entrypoint should expose `build_channel_provider`. Pal calls it with name-aware injection. Useful argument names are:

- `context`: `ChannelProviderBuildContext`
- `manager`: the `ChannelEndpointProviderManager`
- `runtime_root`: the Pal runtime root
- `provider_dir`: this provider directory
- `manifest`: the parsed `RuntimeChannelProviderManifest`

Minimal `runtime.py` using `FactoryChannelProvider`:

```python
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from pal.channel import ChannelEndpointQueueBase, EndpointConfig, FactoryChannelProvider
from pal.channel.models import ChannelEndpointModel


class DemoChatEndpoint(ChannelEndpointQueueBase):
    def normalize_raw(self, payload: Any) -> dict[str, Any]:
        if isinstance(payload, dict):
            return {"text": str(payload.get("text") or "")}
        return {"text": str(payload)}

    def send_reply(self, response_handle, text: str) -> None:
        # Replace this with the transport send path for the channel.
        _ = response_handle, text

    def inspect_health(self) -> dict[str, Any]:
        return {
            "healthy": True,
            "channel_kind": self.endpoint.channel_kind,
            "endpoint_id": self.endpoint.endpoint_id,
        }

    def inspect_auth_state(self) -> dict[str, Any]:
        return {
            "authorized": bool(self.paired),
            "endpoint_id": self.endpoint.endpoint_id,
        }


@dataclass(frozen=True)
class DemoChatEndpointFactory:
    channel_kind: str = "demo_chat"
    reload_modules: tuple[str, ...] = ("runtime",)

    def create(self, record: ChannelEndpointModel, *, runtime_root: Path):
        _ = runtime_root
        endpoint = DemoChatEndpoint(
            endpoint=EndpointConfig(
                endpoint_id=record.endpoint_id,
                channel_kind=record.channel_kind,
                binding_key=record.binding_key,
                send_policy=dict(record.send_policy_blob or {}),
            )
        )
        endpoint.enabled = bool(record.enabled)
        endpoint.attached = record.detached_at is None
        endpoint.paired = bool((record.binding_metadata or {}).get("paired", False))
        return endpoint


def build_channel_provider(context):
    factory = DemoChatEndpointFactory()
    return FactoryChannelProvider(
        provider_id=context.manifest.provider_id,
        endpoint_types=(factory.channel_kind,),
        factory=factory,
        reload_modules=factory.reload_modules,
    )
```

Use a custom `ChannelProvider` implementation instead of `FactoryChannelProvider` when the channel needs provider-owned attach/detach semantics, external sidecars, multi-step auth, pairing flows, or nonstandard introspection.

## Endpoint Row

The provider only handles endpoint types it declares in `endpoint_types`. A usable endpoint still needs a `channel_endpoints` row:

- `endpoint_id`: stable unique id, such as `demo_chat_main`.
- `channel_kind`: endpoint type key, such as `demo_chat`; this must match the provider's endpoint type.
- `binding_key`: channel-specific target, path, chat id, workspace id, or account binding.
- `enabled`: true when Pal should hydrate the endpoint.
- `binding_metadata`: channel-owned structured metadata; do not store raw secrets unless the existing channel explicitly does so.
- `send_policy_blob`: optional delivery/chunking policy.

If there is no endpoint-management capability for the needed row, prepare a clear SQL or repository patch and ask before mutating the production database.

## Interactions and Commands

Control interactions are channel-neutral. Prefer the base `ChannelEndpointQueueBase` hooks first:

- `apply_control_catalog`
- `apply_interaction_status`
- `open_or_update_interaction`
- `resolve_interaction`
- `emit_interaction_result`

Only override channel-specific rendering, such as inline keyboards, slash-command menus, callback payloads, receipts, typing indicators, or transport-specific message editing. Avoid hard-coding Telegram-only assumptions into shared control or core code.

The shared contract is typed data, not UI widgets. Core/control may produce `InteractionMessageSpec`, `InteractionButtonSpec`, `InteractionResult`, status kinds, attachments, and text; the provider decides how those become inline keyboards, menus, edits, reactions, receipts, native commands, or no-op fallbacks. Do not introduce channel-specific callback payloads, button shapes, or slash-command parsing into `core`, `control`, `minion`, `llm`, or `memory`.

## Lifecycle and Hot Reload

Provider rescan means:

1. Scan `<runtime_root>/channel/providers/*/provider.toml`.
2. Load enabled providers not already registered.
3. Register provider ids and endpoint type ownership in `ChannelEndpointProviderManager`.
4. Optionally hydrate enabled, attached endpoint rows.
5. Republish channel introspection capabilities so LLM can see new endpoint ids.

Endpoint restart means rebuilding a runtime endpoint instance through its provider. Do not use endpoint restart as provider discovery.

Useful operations:

- `op_channel_provider_rescan`: discover runtime-root channel providers and optionally attach enabled endpoints.
- `intro_module_channel_list`: list configured channel endpoints and provider ids.
- `intro_endpoint_channel_inspect`: inspect one endpoint.
- `intro_endpoint_channel_auth_state`: inspect authorization without revealing secrets.
- `intro_endpoint_channel_health`: inspect network and delivery health.
- `intro_endpoint_channel_backlog`: inspect queue sizes.
- `op_channel_mgmt_attach`: attach one endpoint through its provider.
- `op_channel_mgmt_detach`: detach one endpoint through its provider.
- `op_channel_mgmt_reload_provider`: restart one endpoint runtime instance.

## Verification Workflow

Before calling a channel provider done:

1. Inspect current channel provider manager and endpoint contracts.
2. Write `provider.toml` and provider source under `<runtime_root>/channel/providers/<provider_id>/`.
3. Compile provider source with `python -m py_compile`.
4. Test provider loading in isolation or with a temporary runtime root first.
5. Add or preview the `channel_endpoints` row for the provider's endpoint type.
6. Run `op_channel_provider_rescan` and check `runtime_provider_load_errors`.
7. Verify `intro_module_channel_list` shows `provider_id`.
8. Verify endpoint `inspect`, `auth_state`, `health`, and `backlog`.
9. Dogfood through the real channel if safe; for socket, send `/control` before sending LLM-consuming messages.
10. Detach and attach the endpoint once to prove provider-owned lifecycle is reversible.

## Safety Notes

- Do not expose tokens or secrets in introspection payloads.
- Do not start multiple long-polling instances for the same external account or Telegram bot token.
- Do not silently mutate production channel endpoint rows, credentials, or live polling state without user approval.
- Keep provider failures structured and visible through `runtime_provider_load_errors` or endpoint health.
- Prefer small deterministic transport adapters. Put large protocol clients or sidecars behind provider-owned lifecycle code.
- A provider that touches hardware, local IPC, OS devices, sensors, cameras, microphones, serial ports, GPIO, Bluetooth, or other privileged resources must make that ownership explicit in introspection and cleanly release the resource on detach/reload.
- Ingress should attach a provider-owned `control_scope_key` when it needs custom conversation grouping. Shared routing must consume that key without understanding the channel's internal identifiers.
"""


PAL_LSP_TEMPLATE_DEVELOPMENT_MANUAL = """# Pal LSP Template and Language Environment Development

Use this skill when Pal needs to add, review, repair, or explain support for a new language server, LSP server template, or minion workspace language setup.

## Boundary

LSP server templates are runtime configuration, not core code. Prefer creating or updating a runtime template under:

```text
<runtime_root>/plugins/lsp/servers/<server_id>.toml
```

Do not edit package builtin templates under `src/pal/lsp/server_templates/` unless the user is intentionally upstreaming a first-party default. Runtime templates override builtin templates with the same `server_id`, matching the LSP manager's normal discovery behavior.

Language environment preparation is code only when the language needs repo files or setup beyond a server template. Keep this in `src/pal/minion/workspace_environment.py` through the `WorkspaceEnvironmentPreparer` shape. Do not add language-specific logic to `git_env.py`; git env should only call the general workspace environment hook.

## Runtime Template Shape

Create a small TOML file with this shape:

```toml
server_id = "example_ls"
display_name = "Example Language Server"
command = ["example-language-server"]
args = ["--stdio"]
extensions = [".example"]
language_ids = ["example"]
workspace_markers = ["example.toml", ".git"]
install_hint = "Install example-language-server and ensure it is on PATH."
startup_timeout_ms = 30000
diagnostics_timeout_ms = 10000
```

Fields:

- `server_id`: stable unique id. Use lowercase, underscores, or hyphens.
- `command`: argv list, not a shell string.
- `args`: argv list. Include stdio flags when the server needs them.
- `extensions`: file extensions including the dot.
- `language_ids`: canonical ids used by planner `metadata.languages` and workspace setup.
- `workspace_markers`: files/directories that identify a workspace root.
- `install_hint`: concrete install guidance without secrets.
- timeouts: raise startup/diagnostics timeouts for npx, JVM, or slow indexers.

For npm-distributed servers, prefer the npx sidecar route:

```toml
command = ["npx"]
args = ["--yes", "--package", "some-language-server", "some-language-server", "--stdio"]
startup_timeout_ms = 60000
diagnostics_timeout_ms = 10000
```

Pal sidecars already prepare PATH for common Node/nvm installs. Do not shell-wrap npx.

## Language Environment Code

The template-backed fallback lets a new language work when a runtime LSP template advertises a matching `language_ids` entry. Add code only when one of these is true:

- The language needs repo config at creation time, such as `.clangd`, `compile_commands.json`, `pyrightconfig.json`, project files, or generated marker files.
- Planner/module path inference needs new extension aliases in `LANGUAGE_EXTENSIONS`.
- Common user spelling needs a new canonical alias in `LANGUAGE_ALIASES`.
- Review/coder setup needs a language-specific skip reason, baseline file, or server mapping beyond the generic template fallback.

When code is needed:

1. Add a focused `WorkspaceEnvironmentPreparer` class in `src/pal/minion/workspace_environment.py`.
2. Set `language_ids` to the canonical ids and `required_lsp_server_ids` to matching template server ids.
3. Implement `prepare(context)` so it is idempotent and never overwrites user files.
4. Return `WorkspaceEnvironmentPatch(server_ids=[...], created_files=[...], skipped=[...])`.
5. Register the preparer in `PREPARERS`.
6. Keep any created repo files small and deterministic.
7. Let `git_env.py` commit created files into the workspace baseline; do not call git from the preparer.

## Workflow

1. Inspect existing templates with `op_lsp_status`, source, or file reads.
2. Choose the canonical `language_id` the planner should emit in `metadata.languages`.
3. Write the runtime template to `<runtime_root>/plugins/lsp/servers/<server_id>.toml`.
4. If needed, add aliases/extensions/preparer code in `workspace_environment.py`.
5. Validate the template with `pal.lsp.config.load_lsp_server_file` or an isolated unit test.
6. Run the focused workspace environment tests for template-backed setup and any new preparer behavior.
7. Run LSP rescan through `op_lsp_mgmt_rescan` when the running Pal runtime should see the new template.
8. Verify with `op_lsp_status`, `op_lsp_doctor`, and a representative diagnostics/hover request when a sample file exists.

## Safety

- Do not install language servers unless the user approved dependency installation.
- Do not write secrets, credentials, or user-specific absolute paths into templates.
- Do not overwrite an existing runtime template without comparing it first.
- Do not create repo setup files for existing repos unless the workspace environment hook is explicitly creating a new task repo or the user asked for that change.
- If a binary is missing, leave a clear `install_hint` and report the missing dependency; missing binaries should be visible as LSP health, not crash Pal.

## Verification Checklist

Before calling the language support done:

1. Runtime template file exists at `<runtime_root>/plugins/lsp/servers/<server_id>.toml`.
2. `load_lsp_server_file` parses it and preserves command, args, extensions, language_ids, markers, and timeouts.
3. `prepare_workspace_environment(..., runtime_root=...)` maps the new `metadata.languages` id to the server id.
4. Any language-specific preparer is covered by a focused test and does not overwrite existing files.
5. `op_lsp_mgmt_rescan` succeeds when the user wants the running runtime refreshed.
6. `op_lsp_doctor` reports ok, missing_binary, disabled, or another structured status instead of failing unstructured.
7. The handoff lists the template path, server id, language id, any code changes, tests run, and any dependency still missing.
"""


def builtin_declared_skills(*, module_id: str = "skill") -> tuple[SkillDescriptor, ...]:
    return (
        SkillDescriptor(
            skill_id=PAL_PLUGIN_DEVELOPMENT_SKILL_ID,
            module_id=module_id,
            title="Pal Plugin Development",
            summary="Develop, review, and hot-refresh Pal plugins without direct source-code access.",
            manual_text=PAL_PLUGIN_DEVELOPMENT_MANUAL,
            activation_terms=(
                "pal plugin",
                "plugin development",
                "develop plugin",
                "create plugin",
                "extend capability",
                "capability extension",
                "build_plugin",
                "ModuleHandle",
                "capability_node",
                "capability_action",
                "hot refresh",
            ),
            capability_refs=(
                "op_plugin_mgmt_rescan",
                "op_plugin_mgmt_attach",
                "op_plugin_mgmt_detach",
                "op_plugin_mgmt_enable",
                "op_tool_search",
                "op_tool_call",
            ),
            applicability_star=SkillApplicabilitySTAR(
                situation="Pal needs to extend itself through a plugin or understand an existing plugin boundary.",
                task="Create or repair a detachable plugin with capabilities and clean lifecycle behavior.",
                action="Use the plugin layout, build_plugin contract, ModuleHandle surfaces, and verification checklist.",
                result="The plugin attaches cleanly, exposes discoverable capabilities, and hot-refreshes without core edits.",
            ),
            use_when=(
                "Use when the user asks Pal to add a plugin, extend capabilities, repair plugin hot refresh, "
                "or explain how a Pal plugin should be structured."
            ),
            avoid_when="Avoid when the change clearly belongs in core runtime contracts or security policy.",
            source_format="internal_skill",
            source_refs=("pal.skill.builtin_skills",),
            metadata={"internal": True},
        ),
        SkillDescriptor(
            skill_id=PAL_LLM_ADAPTER_ENDPOINT_DEVELOPMENT_SKILL_ID,
            module_id=module_id,
            title="Pal LLM Adapter and Endpoint Development",
            summary="Develop and validate runtime-root LLM provider adapters and matching endpoint rows safely.",
            manual_text=PAL_LLM_ADAPTER_ENDPOINT_DEVELOPMENT_MANUAL,
            activation_terms=(
                "llm adapter",
                "llm endpoint",
                "provider adapter",
                "endpoint adapter",
                "runtime adapter",
                "litellm adapter",
                "new model provider",
                "add llm provider",
                "pal.llm_provider_adapters",
                "llm/adapters",
                "refresh_llm_endpoints",
            ),
            capability_refs=(
                "intro_module_llm_list",
                "intro_module_llm_show",
                "op_llm_mgmt_set_active_endpoint",
            ),
            applicability_star=SkillApplicabilitySTAR(
                situation="Pal needs to integrate a new LLM provider or repair endpoint-specific request serialization.",
                task="Create or update a runtime-root LLM adapter and matching endpoint metadata without destabilizing PalCore.",
                action="Use the adapter contract, endpoint checklist, isolated tests, and user-controlled refresh handoff.",
                result="The adapter and endpoint are ready to load, with tests completed and production refresh left to the user.",
            ),
            use_when=(
                "Use when the user asks Pal to add an LLM adapter, add an LLM endpoint, fix provider-specific LiteLLM "
                "serialization, or prepare a new model provider integration."
            ),
            avoid_when=(
                "Avoid for Pal plugins, channel endpoints such as Telegram/socket, or ordinary endpoint switching that "
                "does not require adapter code."
            ),
            source_format="internal_skill",
            source_refs=("pal.skill.builtin_skills", "docs/pal_llm_contract.md"),
            metadata={"internal": True, "requires_user_refresh": True},
        ),
        SkillDescriptor(
            skill_id=PAL_CHANNEL_PROVIDER_DEVELOPMENT_SKILL_ID,
            module_id=module_id,
            title="Pal Channel Provider Development",
            summary="Develop and validate runtime-root channel providers, endpoint rows, and channel-specific interactions.",
            manual_text=PAL_CHANNEL_PROVIDER_DEVELOPMENT_MANUAL,
            activation_terms=(
                "channel provider",
                "channel endpoint",
                "channel integration",
                "new channel",
                "add channel",
                "runtime channel provider",
                "channel/providers",
                "provider.toml",
                "ChannelEndpointProviderManager",
                "FactoryChannelProvider",
                "ChannelEndpointQueueBase",
                "telegram channel",
                "socket channel",
            ),
            capability_refs=(
                "op_channel_provider_rescan",
                "intro_module_channel_list",
                "intro_endpoint_channel_inspect",
                "intro_endpoint_channel_auth_state",
                "intro_endpoint_channel_health",
                "intro_endpoint_channel_backlog",
                "op_channel_mgmt_attach",
                "op_channel_mgmt_detach",
                "op_channel_mgmt_reload_provider",
            ),
            applicability_star=SkillApplicabilitySTAR(
                situation="Pal needs to add or repair a channel integration without pushing transport details into core.",
                task="Create a runtime-root channel provider, endpoint implementation, and matching endpoint metadata.",
                action="Use the provider.toml layout, build_channel_provider contract, lifecycle boundary, and dogfood checklist.",
                result="The channel provider rescans, hydrates endpoints, exposes provider-owned introspection, and can be attached or detached safely.",
            ),
            use_when=(
                "Use when the user asks Pal to create, review, repair, or hot-load a channel provider, channel endpoint, "
                "slash-command handling path, inline interaction rendering, or runtime-root channel integration."
            ),
            avoid_when=(
                "Avoid for ordinary Pal plugins, LLM provider adapters, or changes that only switch an existing endpoint "
                "without adding provider or endpoint code."
            ),
            sanitization_notes=(
                "Provider secrets must remain write-only.",
                "Live polling or external account attachment needs explicit user approval.",
            ),
            source_format="internal_skill",
            source_refs=("pal.skill.builtin_skills", "src/pal/channel/README.md"),
            metadata={"internal": True, "runtime_root_layout": "channel/providers/<provider_id>/provider.toml"},
        ),
        SkillDescriptor(
            skill_id=PAL_LSP_TEMPLATE_DEVELOPMENT_SKILL_ID,
            module_id=module_id,
            title="Pal LSP Template and Language Environment Development",
            summary="Develop runtime-root LSP server templates and matching minion workspace language setup code.",
            manual_text=PAL_LSP_TEMPLATE_DEVELOPMENT_MANUAL,
            activation_terms=(
                "lsp template",
                "language server template",
                "new language lsp",
                "add language support",
                "lsp server",
                "plugins/lsp/servers",
                "workspace environment preparer",
                "WorkspaceEnvironmentPreparer",
                "language_ids",
                "op_lsp_mgmt_rescan",
                "language server",
            ),
            capability_refs=(
                "op_lsp_mgmt_rescan",
                "op_lsp_status",
                "op_lsp_doctor",
                "op_lsp_diagnostics",
            ),
            applicability_star=SkillApplicabilitySTAR(
                situation="Pal needs to add or repair LSP support for a programming language.",
                task="Create a runtime-root LSP server template and any required workspace environment preparer code.",
                action="Use the template shape, runtime config path, preparer contract, and verification checklist.",
                result="The language is visible to LSP discovery and minion workspace setup without changing git_env.",
            ),
            use_when=(
                "Use when the user asks Pal to add a language server, support a new language in LSP/minion review, "
                "create an LSP template, or add workspace environment setup for a language."
            ),
            avoid_when=(
                "Avoid for ordinary plugin development, LLM adapters, channel providers, or one-off project files "
                "that do not add reusable LSP/language support."
            ),
            source_format="internal_skill",
            source_refs=(
                "pal.skill.builtin_skills",
                "src/pal/lsp/config.py",
                "src/pal/minion/workspace_environment.py",
                "docs/pal_engineering_quality_gates.md",
            ),
            metadata={
                "internal": True,
                "runtime_root_layout": "plugins/lsp/servers/<server_id>.toml",
                "may_require_code_changes": True,
            },
        ),
    )
