from __future__ import annotations

from pal.skill.contracts import SkillApplicabilitySTAR, SkillDescriptor


PAL_PLUGIN_DEVELOPMENT_SKILL_ID = "pal.plugin.development"


PAL_PLUGIN_DEVELOPMENT_MANUAL = """# Pal Plugin Development

Use this skill when Pal needs to create, review, repair, or explain a Pal plugin and cannot rely on direct source-code access.

## Goal

A Pal plugin is a sidecar extension that adds capabilities, prompt fragments, providers, event sources, event handlers, or control handlers without editing Pal core. Prefer a plugin when the requested feature is optional, detachable, hot-refreshable, or owned by a domain boundary outside core.

Do not make a plugin for behavior that belongs in the runtime bus itself, the shared message contracts, or the security/control plane. Core should stay a coordinator; plugins should own feature behavior.

## Community Plugin Layout

Put community plugins under the runtime root:

```text
<runtime_root>/plugins/community/<plugin_id>/
  plugin.toml
  runtime.py
  introspection.py        # optional, but recommended for capability providers
  README.md              # optional human notes
```

Use a unique `plugin_id`. Avoid reusing first-party IDs.

Minimal `plugin.toml`:

```toml
plugin_id = "demo_tools"
entrypoint = "runtime"
version = "0.1.0"
enabled_by_default = true
```

Optional:

```toml
reload_modules = ["runtime", "introspection"]
```

For community plugins, Pal clears modules loaded from the plugin directory during refresh. `reload_modules` is still useful when the plugin imports helper modules through stable names.

## Runtime Entrypoint

The entrypoint module must expose `build_plugin`. Pal calls it by name-aware dependency injection. Supported argument names include:

- `context`: a `PluginBuildContext` containing `runtime_root`, `services`, and `plugin_dir`.
- `runtime_root`: the Pal runtime root path.
- `plugin_dir`: this plugin directory.
- any service name present in the plugin host service map, such as `memory_service`.

Example `runtime.py`:

```python
from dataclasses import dataclass

from pal.core.module_registry import MODULE_TIER_DETACHABLE, ModuleHandle
from introspection import DemoProvider


@dataclass
class DemoPluginBundle:
    plugin_id: str = "demo_tools"
    version: str = "0.1.0"

    def register_with_core(self, context):
        provider = DemoProvider()
        handle = ModuleHandle(
            module_id="demo_tools",
            tier=MODULE_TIER_DETACHABLE,
            detachable=True,
            introspection_provider=provider,
            supports_lifecycle_capabilities=True,
        )
        context.register_module(handle)
        return handle


def build_plugin(context=None, runtime_root=None, plugin_dir=None):
    return DemoPluginBundle()
```

## Capability Provider

Expose operations by combining `@capability_node` on the provider class and `@capability_action` on methods. Use `CapabilityCall` for operation calls and return `CapabilityResult` with non-empty `llm_text`.

Example `introspection.py`:

```python
from dataclasses import dataclass

from pal.execution.contracts import CapabilityCall, CapabilityResult
from pal.shared import OPERATION_NAMESPACE, RuntimeStatus, capability_action, capability_node


@capability_node(
    namespace=OPERATION_NAMESPACE,
    scope="module",
    kind="module",
    source="plugin:demo_tools",
    target_kind="module",
)
@dataclass
class DemoProvider:
    module_id: str = "demo_tools"

    @capability_action(
        namespace=OPERATION_NAMESPACE,
        scope="module",
        family="demo",
        action_name="echo",
        description="Echo a short message.",
        args_schema={
            "type": "object",
            "properties": {"message": {"type": "string"}},
            "required": ["message"],
        },
        metadata={"llm_exposed": True},
    )
    def echo(self, call: CapabilityCall) -> CapabilityResult:
        message = str(call.args.get("message") or "")
        return CapabilityResult(
            status=RuntimeStatus.OK,
            text=message,
            structured={"message": message},
            llm_text=f"Echo: {message}",
        )
```

The canonical capability name is generated by the capability forest. Search for it with `op_exec_disc_search` instead of guessing.

## Registering Other Surfaces

`ModuleHandle` is the plugin's contract with core:

- `introspection_provider`: capability provider.
- `prompt_fragment_providers`: prompt fragments owned by this module.
- `event_sources`: event sources owned by this module.
- `event_handlers`: event handlers keyed by event kind.
- `control_action_handlers`: deterministic control action handlers.
- `provider_refs`: named providers that execution runtime may route to.
- `ports`: internal service ports exposed as `<module_id>:<port_name>`.
- `cleanup_callbacks`: cleanup functions called on detach.

Keep each surface owned by the plugin's `module_id` so detach can withdraw the full subtree.

## Lifecycle and Hot Refresh

Attach, detach, and reattach must be clean:

1. Build a fresh bundle through `build_plugin`.
2. Return a `ModuleHandle` whose module ID is stable.
3. Let core/plugin host publish and withdraw capabilities; do not manually mutate the compiled index.
4. Put external resources in `cleanup_callbacks` or provider `detach` methods.
5. After code changes, use plugin detach/attach or core module reattach to load a fresh instance.

Useful operations:

- `op_plugin_mgmt_rescan`: discover plugin manifests.
- `op_plugin_mgmt_attach`: attach or refresh a plugin.
- `op_plugin_mgmt_detach`: detach a plugin.
- `op_plugin_mgmt_enable`: enable and attach a disabled plugin.
- `op_exec_disc_search`: find capabilities after attach.
- `op_exec_capability_call`: call a capability by discovered name.

## Safety and Product Rules

- Do not ask the user to do work Pal can do with existing capabilities.
- Do not bypass approval, access, identity, or constitutional boundaries.
- For high-risk actions, destructive filesystem changes, credentials, public network changes, or persistent system changes, route through the control/approval path.
- Keep large outputs in files or artifacts. Return short summaries and file paths.
- Prefer structured APIs over fragile string scraping.
- Keep plugin state in plugin-owned storage or the runtime root, not in Pal core globals.
- Use stable, minimal capability schemas. A small predictable tool beats a broad ambiguous one.

## Verification Checklist

Before calling the plugin done:

1. `op_plugin_mgmt_rescan` sees the manifest with no scan errors.
2. `op_plugin_mgmt_attach` returns ok and the plugin record is attached.
3. `op_exec_disc_search` finds the new capability or prompt/source surface.
4. A representative capability call returns structured data and useful `llm_text`.
5. Detach removes the capability from discovery.
6. Attach again creates a fresh instance and restores the capability.
7. The plugin does not require the user to run commands manually unless approval or credentials are genuinely needed.
"""


def builtin_declared_skills(*, module_id: str = "skill") -> tuple[SkillDescriptor, ...]:
    return (
        SkillDescriptor(
            skill_id=PAL_PLUGIN_DEVELOPMENT_SKILL_ID,
            module_id=module_id,
            title="Pal Plugin Development",
            summary="Develop, review, and hot-refresh Pal plugins without direct source-code access.",
            manual_text=PAL_PLUGIN_DEVELOPMENT_MANUAL,
            activation_terms=(
                "pal plugin",
                "plugin development",
                "develop plugin",
                "create plugin",
                "extend capability",
                "capability extension",
                "build_plugin",
                "ModuleHandle",
                "capability_node",
                "capability_action",
                "hot refresh",
            ),
            capability_refs=(
                "op_plugin_mgmt_rescan",
                "op_plugin_mgmt_attach",
                "op_plugin_mgmt_detach",
                "op_plugin_mgmt_enable",
                "op_exec_disc_search",
                "op_exec_capability_call",
            ),
            applicability_star=SkillApplicabilitySTAR(
                situation="Pal needs to extend itself through a plugin or understand an existing plugin boundary.",
                task="Create or repair a detachable plugin with capabilities and clean lifecycle behavior.",
                action="Use the plugin layout, build_plugin contract, ModuleHandle surfaces, and verification checklist.",
                result="The plugin attaches cleanly, exposes discoverable capabilities, and hot-refreshes without core edits.",
            ),
            use_when=(
                "Use when the user asks Pal to add a plugin, extend capabilities, repair plugin hot refresh, "
                "or explain how a Pal plugin should be structured."
            ),
            avoid_when="Avoid when the change clearly belongs in core runtime contracts or security policy.",
            source_format="internal_skill",
            source_refs=("pal.skill.builtin_skills",),
            metadata={"internal": True},
        ),
    )
