from __future__ import annotations

from pal.skill.contracts import SkillApplicabilitySTAR, SkillDescriptor


PAL_PLUGIN_DEVELOPMENT_SKILL_ID = "pal.plugin.development"
PAL_LLM_ADAPTER_ENDPOINT_DEVELOPMENT_SKILL_ID = "pal.llm.adapter_endpoint.development"


PAL_PLUGIN_DEVELOPMENT_MANUAL = """# Pal Plugin Development

Use this skill when Pal needs to create, review, repair, or explain a Pal plugin and cannot rely on direct source-code access.

## Goal

A Pal plugin is a sidecar extension that adds capabilities, prompt fragments, providers, event sources, event handlers, or control handlers without editing Pal core. Prefer a plugin when the requested feature is optional, detachable, hot-refreshable, or owned by a domain boundary outside core.

Do not make a plugin for behavior that belongs in the runtime bus itself, the shared message contracts, or the security/control plane. Core should stay a coordinator; plugins should own feature behavior.

## Community Plugin Layout

Put community plugins under the runtime root:

```text
<runtime_root>/plugins/community/<plugin_id>/
  plugin.toml
  runtime.py
  introspection.py        # optional, but recommended for capability providers
  README.md              # optional human notes
```

Use a unique `plugin_id`. Avoid reusing first-party IDs.

Minimal `plugin.toml`:

```toml
plugin_id = "demo_tools"
entrypoint = "runtime"
version = "0.1.0"
enabled_by_default = true
```

Optional:

```toml
reload_modules = ["runtime", "introspection"]
```

For community plugins, Pal clears modules loaded from the plugin directory during refresh. `reload_modules` is still useful when the plugin imports helper modules through stable names.

## Runtime Entrypoint

The entrypoint module must expose `build_plugin`. Pal calls it by name-aware dependency injection. Supported argument names include:

- `context`: a `PluginBuildContext` containing `runtime_root`, `services`, and `plugin_dir`.
- `runtime_root`: the Pal runtime root path.
- `plugin_dir`: this plugin directory.
- any service name present in the plugin host service map, such as `memory_service`.

Example `runtime.py`:

```python
from dataclasses import dataclass

from pal.core.module_registry import MODULE_TIER_DETACHABLE, ModuleHandle
from introspection import DemoProvider


@dataclass
class DemoPluginBundle:
    plugin_id: str = "demo_tools"
    version: str = "0.1.0"

    def register_with_core(self, context):
        provider = DemoProvider()
        handle = ModuleHandle(
            module_id="demo_tools",
            tier=MODULE_TIER_DETACHABLE,
            detachable=True,
            introspection_provider=provider,
            supports_lifecycle_capabilities=True,
        )
        context.register_module(handle)
        return handle


def build_plugin(context=None, runtime_root=None, plugin_dir=None):
    return DemoPluginBundle()
```

## Capability Provider

Expose operations by combining `@capability_node` on the provider class and `@capability_action` on methods. Use `CapabilityCall` for operation calls and return `CapabilityResult` with non-empty `llm_text`.

Example `introspection.py`:

```python
from dataclasses import dataclass

from pal.execution.contracts import CapabilityCall, CapabilityResult
from pal.shared import OPERATION_NAMESPACE, RuntimeStatus, capability_action, capability_node


@capability_node(
    namespace=OPERATION_NAMESPACE,
    scope="module",
    kind="module",
    source="plugin:demo_tools",
    target_kind="module",
)
@dataclass
class DemoProvider:
    module_id: str = "demo_tools"

    @capability_action(
        namespace=OPERATION_NAMESPACE,
        scope="module",
        family="demo",
        action_name="echo",
        description="Echo a short message.",
        args_schema={
            "type": "object",
            "properties": {"message": {"type": "string"}},
            "required": ["message"],
        },
    )
    def echo(self, call: CapabilityCall) -> CapabilityResult:
        message = str(call.args.get("message") or "")
        return CapabilityResult(
            status=RuntimeStatus.OK,
            text=message,
            structured={"message": message},
            llm_text=f"Echo: {message}",
        )
```

The canonical capability name is generated by the capability forest. Search for it with `op_tool_search` instead of guessing.

## Registering Other Surfaces

`ModuleHandle` is the plugin's contract with core:

- `introspection_provider`: capability provider.
- `prompt_fragment_providers`: prompt fragments owned by this module.
- `event_sources`: event sources owned by this module.
- `event_handlers`: event handlers keyed by event kind.
- `control_action_handlers`: deterministic control action handlers.
- `provider_refs`: named providers that execution runtime may route to.
- `ports`: internal service ports exposed as `<module_id>:<port_name>`.
- `cleanup_callbacks`: cleanup functions called on detach.

Keep each surface owned by the plugin's `module_id` so detach can withdraw the full subtree.

## Lifecycle and Hot Refresh

Attach, detach, and reattach must be clean:

1. Build a fresh bundle through `build_plugin`.
2. Return a `ModuleHandle` whose module ID is stable.
3. Let core/plugin host publish and withdraw capabilities; do not manually mutate the compiled index.
4. Put external resources in `cleanup_callbacks` or provider `detach` methods.
5. After code changes, use plugin detach/attach or core module reattach to load a fresh instance.

Useful operations:

- `op_plugin_mgmt_rescan`: discover plugin manifests.
- `op_plugin_mgmt_attach`: attach or refresh a plugin.
- `op_plugin_mgmt_detach`: detach a plugin.
- `op_plugin_mgmt_enable`: enable and attach a disabled plugin.
- `op_tool_search`: find capabilities after attach.
- `op_tool_call`: call a capability by discovered name.

## Safety and Product Rules

- Do not ask the user to do work Pal can do with existing capabilities.
- Do not bypass approval, access, identity, or constitutional boundaries.
- For high-risk actions, destructive filesystem changes, credentials, public network changes, or persistent system changes, route through the control/approval path.
- Keep large outputs in files or artifacts. Return short summaries and file paths.
- Prefer structured APIs over fragile string scraping.
- Keep plugin state in plugin-owned storage or the runtime root, not in Pal core globals.
- Use stable, minimal capability schemas. A small predictable tool beats a broad ambiguous one.

## Verification Checklist

Before calling the plugin done:

1. `op_plugin_mgmt_rescan` sees the manifest with no scan errors.
2. `op_plugin_mgmt_attach` returns ok and the plugin record is attached.
3. `op_tool_search` finds the new capability or prompt/source surface.
4. A representative capability call returns structured data and useful `llm_text`.
5. Detach removes the capability from discovery.
6. Attach again creates a fresh instance and restores the capability.
7. The plugin does not require the user to run commands manually unless approval or credentials are genuinely needed.
"""


PAL_LLM_ADAPTER_ENDPOINT_DEVELOPMENT_MANUAL = """# Pal LLM Adapter and Endpoint Development

Use this skill when Pal needs to add, review, repair, or explain an LLM provider adapter and its matching `llm_endpoints` row.

## Boundary

LLM provider adapters belong to the `llm` subsystem, not the plugin system. Do not create a Pal plugin for LLM transport behavior. Do not register adapters through `PluginHost`, `PluginBuildContext.services`, capability providers, prompt fragments, or global side effects outside `pal.llm`.

The production refresh/load step is user-controlled. You may prepare files, propose endpoint rows, and run isolated tests, but you must not execute `/refresh_llm_endpoints`, call `refresh_llm_endpoints`, set the active endpoint, or otherwise load the adapter into the running Pal runtime without explicit user direction. Final handoff must tell the user that refresh is required and list exactly what to refresh.

## Runtime Adapter Location

Put runtime-root adapter source under:

```text
<runtime_root>/llm/adapters/
```

Supported layouts:

```text
<runtime_root>/llm/adapters/my_provider.py
<runtime_root>/llm/adapters/my_provider/adapter.py
```

Each adapter module should define one or more `LLMProviderAdapter` subclasses. Explicit exports are allowed:

```python
ADAPTER = MyProviderAdapter
ADAPTERS = (MyProviderAdapter, OtherProviderAdapter)
```

## Adapter Contract

Keep adapter code small and deterministic. It should translate Pal's canonical request and endpoint metadata into LiteLLM kwargs, not perform network calls, mutate databases, read secrets, or import PalCore internals.

Minimal adapter:

```python
from pal.llm import CanonicalLLMRequest, LLMProviderAdapter, LiteLLMCompletionDraft


class MyProviderAdapter(LLMProviderAdapter):
    provider_names = frozenset({"my_provider"})
    adapter_names = frozenset({"my_provider"})
    litellm_provider = "openai"
    model_provider_aliases = frozenset({"openai"})

    def apply_request(self, request: CanonicalLLMRequest, draft: LiteLLMCompletionDraft) -> None:
        if request.metadata.get("think_level") == "off":
            draft.extra_body["thinking"] = {"type": "disabled"}
```

Use `provider_names` for endpoint `provider` matching. Use `adapter_names` when an endpoint sets `capabilities_blob.adapter` or `capabilities_blob.llm_adapter`. Use `litellm_provider` and `model_provider_aliases` to normalize `model_id` into the provider prefix LiteLLM expects.

## Endpoint Row

Create or update endpoint metadata only after checking the existing endpoint list. Required fields include:

- `endpoint_id`: stable unique ID, such as `my_provider_gpt_5`.
- `provider`: must match the adapter `provider_names` unless `capabilities_blob.adapter` selects the adapter.
- `model_id`: model name or LiteLLM-prefixed model, such as `my-model` or `openai/my-model`.
- `api_mode`: normally `openai_chat`; use `anthropic_messages` only for Anthropic-shaped endpoints.
- `base_url`: provider base URL, without credentials.
- `auth_kind`: `api_key_ref`, `oauth`, or `local_provider_auth`.
- `credential_ref`: secret reference such as `my_provider:api-key`; never store the key in the adapter.
- capability flags: `supports_tools`, `supports_streaming`, `supports_reasoning`, `supports_vision`, and optional `capabilities_blob`.

Prefer preparing a clear endpoint patch or SQL preview when no dedicated endpoint-management capability exists. Mutating the production database or secrets requires explicit user approval.

## Verification Workflow

Before asking the user to refresh:

1. Inspect the current `pal.llm.adapters.LLMProviderAdapter` contract and existing endpoint shape.
2. Write adapter source in the runtime-root adapter directory.
3. Compile the adapter file with `python -m py_compile <adapter_file>`.
4. Load it only in an isolated registry or subprocess, not the live Pal runtime.
5. Build a representative `LiteLLMEndpointInvoker(...)._build_completion_kwargs(...)` payload with a fake or test endpoint.
6. Assert model prefix, `api_base`, auth behavior, tools, `tool_choice`, `temperature`, max tokens, reasoning/thinking fields, and vendor-specific `extra_body`.
7. Confirm the adapter does not import plugin, channel, control, service, or PalCore internals.
8. If endpoint metadata changes are needed, verify them against a temporary database or produce an exact patch for user approval.
9. Do not switch the active endpoint during development.

## Handoff

When the adapter and endpoint are ready, report:

- adapter file path and endpoint ID
- tests or smoke checks run
- endpoint/database/secret changes made or still pending
- any load errors found in isolated checks
- a clear statement: "I did not refresh the running Pal runtime. Please run `/refresh_llm_endpoints` when you want to load this adapter."

If the user explicitly asks you to refresh, then use the normal LLM refresh path and report `provider_adapter_load_errors` if present.
"""


def builtin_declared_skills(*, module_id: str = "skill") -> tuple[SkillDescriptor, ...]:
    return (
        SkillDescriptor(
            skill_id=PAL_PLUGIN_DEVELOPMENT_SKILL_ID,
            module_id=module_id,
            title="Pal Plugin Development",
            summary="Develop, review, and hot-refresh Pal plugins without direct source-code access.",
            manual_text=PAL_PLUGIN_DEVELOPMENT_MANUAL,
            activation_terms=(
                "pal plugin",
                "plugin development",
                "develop plugin",
                "create plugin",
                "extend capability",
                "capability extension",
                "build_plugin",
                "ModuleHandle",
                "capability_node",
                "capability_action",
                "hot refresh",
            ),
            capability_refs=(
                "op_plugin_mgmt_rescan",
                "op_plugin_mgmt_attach",
                "op_plugin_mgmt_detach",
                "op_plugin_mgmt_enable",
                "op_tool_search",
                "op_tool_call",
            ),
            applicability_star=SkillApplicabilitySTAR(
                situation="Pal needs to extend itself through a plugin or understand an existing plugin boundary.",
                task="Create or repair a detachable plugin with capabilities and clean lifecycle behavior.",
                action="Use the plugin layout, build_plugin contract, ModuleHandle surfaces, and verification checklist.",
                result="The plugin attaches cleanly, exposes discoverable capabilities, and hot-refreshes without core edits.",
            ),
            use_when=(
                "Use when the user asks Pal to add a plugin, extend capabilities, repair plugin hot refresh, "
                "or explain how a Pal plugin should be structured."
            ),
            avoid_when="Avoid when the change clearly belongs in core runtime contracts or security policy.",
            source_format="internal_skill",
            source_refs=("pal.skill.builtin_skills",),
            metadata={"internal": True},
        ),
        SkillDescriptor(
            skill_id=PAL_LLM_ADAPTER_ENDPOINT_DEVELOPMENT_SKILL_ID,
            module_id=module_id,
            title="Pal LLM Adapter and Endpoint Development",
            summary="Develop and validate runtime-root LLM provider adapters and matching endpoint rows safely.",
            manual_text=PAL_LLM_ADAPTER_ENDPOINT_DEVELOPMENT_MANUAL,
            activation_terms=(
                "llm adapter",
                "llm endpoint",
                "provider adapter",
                "endpoint adapter",
                "runtime adapter",
                "litellm adapter",
                "new model provider",
                "add llm provider",
                "pal.llm_provider_adapters",
                "llm/adapters",
                "refresh_llm_endpoints",
            ),
            capability_refs=(
                "intro_module_llm_list",
                "intro_module_llm_show",
                "op_llm_mgmt_set_active_endpoint",
            ),
            applicability_star=SkillApplicabilitySTAR(
                situation="Pal needs to integrate a new LLM provider or repair endpoint-specific request serialization.",
                task="Create or update a runtime-root LLM adapter and matching endpoint metadata without destabilizing PalCore.",
                action="Use the adapter contract, endpoint checklist, isolated tests, and user-controlled refresh handoff.",
                result="The adapter and endpoint are ready to load, with tests completed and production refresh left to the user.",
            ),
            use_when=(
                "Use when the user asks Pal to add an LLM adapter, add an LLM endpoint, fix provider-specific LiteLLM "
                "serialization, or prepare a new model provider integration."
            ),
            avoid_when=(
                "Avoid for Pal plugins, channel endpoints such as Telegram/socket, or ordinary endpoint switching that "
                "does not require adapter code."
            ),
            source_format="internal_skill",
            source_refs=("pal.skill.builtin_skills", "docs/pal_llm_contract.md"),
            metadata={"internal": True, "requires_user_refresh": True},
        ),
    )
