#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
python_bin="${PYTHON:-python3}"
dist_dir="${1:-$repo_root/dist/providers}"
provider_ids=(telegram websocket_bridge)
staging_root="$(mktemp -d "${TMPDIR:-/tmp}/pal-provider-build.XXXXXX")"

cleanup() {
  rm -rf -- "$staging_root"
}
trap cleanup EXIT

mkdir -p "$dist_dir"
rm -f "$dist_dir"/pal_channel_provider_*.whl

for provider_id in "${provider_ids[@]}"; do
  provider_root="$repo_root/providers/$provider_id"
  staged_provider_root="$staging_root/$provider_id"
  [[ -f "$provider_root/pyproject.toml" ]] || {
    echo "Provider is missing pyproject.toml: $provider_root" >&2
    exit 1
  }
  "$python_bin" - "$provider_root" "$provider_id" <<'PY'
from __future__ import annotations

import sys
import tomllib
from pathlib import Path

root = Path(sys.argv[1])
expected_provider_id = sys.argv[2]
with (root / "pyproject.toml").open("rb") as stream:
    project = dict(tomllib.load(stream).get("project") or {})
with (root / "provider.toml").open("rb") as stream:
    manifest = tomllib.load(stream)
project_version = str(project.get("version") or "").strip()
provider_version = str(manifest.get("version") or "").strip()
provider_id = str(manifest.get("provider_id") or "").strip()
if provider_id != expected_provider_id:
    raise SystemExit(
        f"provider id mismatch for {root}: {provider_id!r} != {expected_provider_id!r}"
    )
if not project_version or project_version != provider_version:
    raise SystemExit(
        f"provider version mismatch for {root}: "
        f"pyproject={project_version!r}, manifest={provider_version!r}"
    )
PY
  mkdir -p "$staged_provider_root"
  for source_file in "$provider_root"/*; do
    if [[ -f "$source_file" ]]; then
      install -m 0644 "$source_file" "$staged_provider_root/$(basename "$source_file")"
    fi
  done
  "$python_bin" -m pip wheel \
    "$staged_provider_root" \
    --no-deps \
    --no-build-isolation \
    -w "$dist_dir"
done

PYTHONPATH="$repo_root/src${PYTHONPATH:+:$PYTHONPATH}" \
  "$python_bin" - "$dist_dir" "${provider_ids[@]}" <<'PY'
from __future__ import annotations

import sys
from pathlib import Path

from pal.provider_install import inspect_provider_wheel

dist_dir = Path(sys.argv[1])
expected_ids = set(sys.argv[2:])
wheels = sorted(dist_dir.glob("pal_channel_provider_*.whl"))
inspected = [inspect_provider_wheel(path) for path in wheels]
actual_ids = {item.provider_id for item in inspected}
if actual_ids != expected_ids:
    raise SystemExit(
        f"provider wheel set mismatch: expected={sorted(expected_ids)}, "
        f"actual={sorted(actual_ids)}"
    )
for item in inspected:
    forbidden = [
        str(path)
        for path in item.payload_files
        if "__pycache__" in path.parts or path.suffix in {".pyc", ".pyo"}
    ]
    if forbidden:
        raise SystemExit(
            f"provider wheel contains generated bytecode: {item.provider_id}: {forbidden}"
        )
    print(
        f"verified provider wheel: {item.provider_id} {item.provider_version} "
        f"({item.wheel_path.name})"
    )
PY
